const QUIZ_CATEGORIES = [
  {
    id: "animals",
    name: "动物",
    nameEn: "Animals",
    icon: "🐾",
    color: "#ff9f43",
    items: [
      { emoji: "🐶", en: "dog",       cn: "狗" },
      { emoji: "🐱", en: "cat",       cn: "猫" },
      { emoji: "🐰", en: "rabbit",    cn: "兔子" },
      { emoji: "🐻", en: "bear",      cn: "熊" },
      { emoji: "🐘", en: "elephant",  cn: "大象" },
      { emoji: "🦁", en: "lion",      cn: "狮子" },
      { emoji: "🐯", en: "tiger",     cn: "老虎" },
      { emoji: "🐵", en: "monkey",    cn: "猴子" },
      { emoji: "🐸", en: "frog",      cn: "青蛙" },
      { emoji: "🐟", en: "fish",      cn: "鱼" },
      { emoji: "🐦", en: "bird",      cn: "鸟" },
      { emoji: "🐢", en: "turtle",    cn: "乌龟" },
      { emoji: "🐍", en: "snake",     cn: "蛇" },
      { emoji: "🐷", en: "pig",       cn: "猪" },
      { emoji: "🐮", en: "cow",       cn: "牛" },
      { emoji: "🐴", en: "horse",     cn: "马" },
      { emoji: "🐑", en: "sheep",     cn: "羊" },
      { emoji: "🦆", en: "duck",      cn: "鸭子" },
      { emoji: "🐧", en: "penguin",   cn: "企鹅" },
      { emoji: "🦊", en: "fox",       cn: "狐狸" },
    ],
  },
  {
    id: "fruits",
    name: "水果",
    nameEn: "Fruits",
    icon: "🍎",
    color: "#ff6b6b",
    items: [
      { emoji: "🍎", en: "apple",       cn: "苹果" },
      { emoji: "🍌", en: "banana",      cn: "香蕉" },
      { emoji: "🍊", en: "orange",      cn: "橙子" },
      { emoji: "🍇", en: "grape",       cn: "葡萄" },
      { emoji: "🍓", en: "strawberry",  cn: "草莓" },
      { emoji: "🍑", en: "peach",       cn: "桃子" },
      { emoji: "🍉", en: "watermelon",  cn: "西瓜" },
      { emoji: "🍒", en: "cherry",      cn: "樱桃" },
      { emoji: "🍍", en: "pineapple",   cn: "菠萝" },
      { emoji: "🥝", en: "kiwi",        cn: "猕猴桃" },
      { emoji: "🍋", en: "lemon",       cn: "柠檬" },
      { emoji: "🥭", en: "mango",       cn: "芒果" },
    ],
  },
  {
    id: "vegetables",
    name: "蔬菜",
    nameEn: "Vegetables",
    icon: "🥦",
    color: "#2ed573",
    items: [
      { emoji: "🥕", en: "carrot",    cn: "胡萝卜" },
      { emoji: "🥦", en: "broccoli",  cn: "西兰花" },
      { emoji: "🌽", en: "corn",      cn: "玉米" },
      { emoji: "🍅", en: "tomato",    cn: "番茄" },
      { emoji: "🥒", en: "cucumber",  cn: "黄瓜" },
      { emoji: "🥬", en: "cabbage",   cn: "白菜" },
      { emoji: "🧅", en: "onion",     cn: "洋葱" },
      { emoji: "🥔", en: "potato",    cn: "土豆" },
      { emoji: "🍄", en: "mushroom",  cn: "蘑菇" },
      { emoji: "🌶️", en: "pepper",    cn: "辣椒" },
    ],
  },
  {
    id: "colors",
    name: "颜色",
    nameEn: "Colors",
    icon: "🎨",
    color: "#a55eea",
    items: [
      { emoji: "❤️", en: "red",     cn: "红色" },
      { emoji: "🧡", en: "orange",  cn: "橙色" },
      { emoji: "💛", en: "yellow",  cn: "黄色" },
      { emoji: "💚", en: "green",   cn: "绿色" },
      { emoji: "💙", en: "blue",    cn: "蓝色" },
      { emoji: "💜", en: "purple",  cn: "紫色" },
      { emoji: "🖤", en: "black",   cn: "黑色" },
      { emoji: "🤍", en: "white",   cn: "白色" },
      { emoji: "🩷", en: "pink",    cn: "粉色" },
      { emoji: "🤎", en: "brown",   cn: "棕色" },
    ],
  },
  {
    id: "body",
    name: "身体",
    nameEn: "Body",
    icon: "🧒",
    color: "#54a0ff",
    items: [
      { emoji: "👀", en: "eye",    cn: "眼睛" },
      { emoji: "👃", en: "nose",   cn: "鼻子" },
      { emoji: "👄", en: "mouth",  cn: "嘴巴" },
      { emoji: "👂", en: "ear",    cn: "耳朵" },
      { emoji: "🖐️", en: "hand",   cn: "手" },
      { emoji: "🦶", en: "foot",   cn: "脚" },
      { emoji: "💪", en: "arm",    cn: "手臂" },
      { emoji: "🦵", en: "leg",    cn: "腿" },
    ],
  },
  {
    id: "numbers",
    name: "数字",
    nameEn: "Numbers",
    icon: "🔢",
    color: "#48dbfb",
    items: [
      { emoji: "1️⃣",  en: "one",    cn: "一" },
      { emoji: "2️⃣",  en: "two",    cn: "二" },
      { emoji: "3️⃣",  en: "three",  cn: "三" },
      { emoji: "4️⃣",  en: "four",   cn: "四" },
      { emoji: "5️⃣",  en: "five",   cn: "五" },
      { emoji: "6️⃣",  en: "six",    cn: "六" },
      { emoji: "7️⃣",  en: "seven",  cn: "七" },
      { emoji: "8️⃣",  en: "eight",  cn: "八" },
      { emoji: "9️⃣",  en: "nine",   cn: "九" },
      { emoji: "🔟", en: "ten",    cn: "十" },
    ],
  },
];

const DIALOGUE_SCENES = [
  {
    id: "greetings",
    name: "打招呼",
    nameEn: "Greetings",
    icon: "👋",
    color: "#ff6b6b",
    dialogues: [
      { cn: "你好！",                 en: "Hello!" },
      { cn: "早上好！",               en: "Good morning!" },
      { cn: "你好吗？",               en: "How are you?" },
      { cn: "我很好，谢谢！",          en: "I'm fine, thank you!" },
      { cn: "再见！",                 en: "Goodbye!" },
      { cn: "晚安！",                 en: "Good night!" },
    ],
  },
  {
    id: "introduce",
    name: "自我介绍",
    nameEn: "About Me",
    icon: "🙋",
    color: "#ff9f43",
    dialogues: [
      { cn: "我叫...",              en: "My name is..." },
      { cn: "我六岁了。",            en: "I am six years old." },
      { cn: "我是一个男孩/女孩。",    en: "I am a boy/girl." },
      { cn: "我喜欢画画。",          en: "I like drawing." },
      { cn: "很高兴认识你！",         en: "Nice to meet you!" },
    ],
  },
  {
    id: "classroom",
    name: "课堂用语",
    nameEn: "In Class",
    icon: "📚",
    color: "#54a0ff",
    dialogues: [
      { cn: "请坐下。",              en: "Please sit down." },
      { cn: "请举手。",              en: "Raise your hand, please." },
      { cn: "打开你的书。",           en: "Open your book." },
      { cn: "我不明白。",            en: "I don't understand." },
      { cn: "请再说一次。",           en: "Say it again, please." },
      { cn: "做得好！",              en: "Well done!" },
    ],
  },
  {
    id: "eating",
    name: "吃饭",
    nameEn: "Eating",
    icon: "🍽️",
    color: "#2ed573",
    dialogues: [
      { cn: "我饿了。",              en: "I am hungry." },
      { cn: "我渴了。",              en: "I am thirsty." },
      { cn: "我想喝水。",            en: "I want some water." },
      { cn: "这个很好吃！",           en: "This is delicious!" },
      { cn: "谢谢你！",              en: "Thank you!" },
      { cn: "不客气！",              en: "You're welcome!" },
    ],
  },
  {
    id: "weather",
    name: "天气",
    nameEn: "Weather",
    icon: "🌤️",
    color: "#48dbfb",
    dialogues: [
      { cn: "今天天气怎么样？",        en: "How is the weather today?" },
      { cn: "今天是晴天。",           en: "It is sunny today." },
      { cn: "今天在下雨。",           en: "It is raining today." },
      { cn: "外面很冷。",            en: "It is cold outside." },
      { cn: "外面很热。",            en: "It is hot outside." },
    ],
  },
  {
    id: "family",
    name: "家人",
    nameEn: "Family",
    icon: "👨‍👩‍👧‍👦",
    color: "#a55eea",
    dialogues: [
      { cn: "这是我的妈妈。",         en: "This is my mom." },
      { cn: "这是我的爸爸。",         en: "This is my dad." },
      { cn: "我爱我的家人。",         en: "I love my family." },
      { cn: "我有一个弟弟/妹妹。",    en: "I have a brother/sister." },
      { cn: "我们一起玩吧！",         en: "Let's play together!" },
    ],
  },
  {
    id: "polite",
    name: "礼貌用语",
    nameEn: "Be Polite",
    icon: "🤝",
    color: "#01a3a4",
    dialogues: [
      { cn: "请。",                  en: "Please." },
      { cn: "谢谢！",               en: "Thank you!" },
      { cn: "对不起。",              en: "I'm sorry." },
      { cn: "没关系。",              en: "That's okay." },
      { cn: "请帮帮我。",            en: "Please help me." },
      { cn: "可以吗？",              en: "May I?" },
    ],
  },
];
